config/routes.rb
Rails.application.routes.draw do
 
  root to: 'users#index'

  get 'signup' => 'users#new', as: :signup 
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  put '/updateRating' => 'thaifoods#updateRating'

  resources :users
  resources :sessions
  resources :comments

  resources :thaifoods do 
  	resources :comments
  end 

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  field :body, type: String
  belongs_to :thaifood

  def date_added
    created_at.locatltime.strftime("%A, %B %-d, %Y at %l:%M %p") 
  end

  belongs_to :user  

  validates :body, presence: true
end

app/models/rating.rb
class Rating
  include Mongoid::Document
  field :rating, type: Integer

  belongs_to :thaifood
  belongs_to :user
end

app/models/thaifood.rb
class Thaifood
	include Mongoid::Document
	include Mongoid::Timestamps
	field :dish, type: String
	field :location, type: String
	field :restaurant, type: String
	field :price_per_dish, type: Float
	field :rating, type: Integer
	mount_uploader :photo, OurImageUploader

	field :body, type: String
	has_many :comments

	validates :dish, presence: true, uniqueness: { case_sensitve: false }
	validates :location, presence: true
	validates :restaurant, presence: true

	def date_published
		created_at.localtime.strftime("%A, %B %-d, %Y at %l:%M %p")
    end 
end 

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  field :email, type: String
  field :firstname, type: String
  field :lastname, type: String
  field :username, type: String
  field :password_digest, type: String
  field :tagline, type: String 
  mount_uploader :photo, OurImageUploader

  validates :email, uniqueness: true
  validates :username, uniqueness: true
  validates :password, confirmation: true
  validates :tagline, uniqueness: { case_sensitve: false}
  
  has_many :comments 
  has_many :ratings  

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
  
  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
  	@comment = Comment.new
  end 

  def create
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.thaifood = Thaifood.find(params[:thaifood_id])
    @comment.user = current_user 
    @comment.save
    redirect_to @comment.thaifood
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
	end 

	def create
		u = User.find_by(email: params[:user][:email])

		if u && u.authenticate(params[:user][:password])
			session[:user_id] = u.id.to_s
			redirect_to thaifoods_path
		else 
			render :new
		end 

	end

	def destroy
		session[:user_id] = nil 
		redirect_to root_path
	end  

end 

app/controllers/thaifoods_controller.rb
class ThaifoodsController < ApplicationController

  def index
    @thaifoods = Thaifood.all
  end

  def show
    @thaifood = Thaifood.find(params[:id])
    @new_comment = @thaifood.comments.new
  end

  def new
    @thaifood = Thaifood.new
  end

  def create
    @thaifood = Thaifood.new(thaifoods_params)

    if @thaifood.save
      redirect_to thaifoods_path
    else
      render :new
    end
  end

  def edit
    @thaifood = Thaifood.find(params[:id])
  end

  def update
    @thaifood = Thaifood.find(params[:id])

    if @thaifood.update(thaifoods_params)
      redirect_to thaifoods_path
    else
      render :edit
    end
  end

  # def updateRating
  #   Thaifood.find(params[:id])
  #    rating + 

  def destroy
    @thaifood = Thaifood.find(params[:id])
    @thaifood.destroy
    redirect_to thaifoods_path
  end

private

  def thaifoods_params
    params.require(:thaifood).permit(:dish, :location, :restaurant, :price_per_dish, :photo, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	end 

	def new
		@user = User.new 
	end 

	def create
		@user = User.new(params.require(:user).permit(:firstname, :lastname, :username, :email, :password, :password_confirmation, :tagline, :photo)) 

		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to thaifoods_path
		else
	 		render :new
	 	end 
	 end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>myThai</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<link href='http://fonts.googleapis.com/css?family=Paytone+One' rel='stylesheet' type='text/css'>
<!-- 
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyCwg6f8ULzlYlD7MfGJdPW6eINlDa_6vUA" %> -->
<body>
  <header class="navbar-default">
    <div class="container">
      <nav role="navigation">
       <div class="navbar-header">
            <a class="navbar-brand" href="users">
              <img src="<%= asset_path('mythai3.svg') %>" alt="myThai">
            </a>
        </div>
        <p class="navbar-text">
          " ...satisfying all your THAI cravings" </P>

              <ul class="nav navbar-nav navbar-right">
                <p class="navbar-text">
                  <% if current_user %>
                  <%= current_user.username %>  <%= link_to "Logout", logout_path %><% else %>
                  <%= link_to "Login", login_path %> - <%= link_to "Signup", signup_path %>
                  <% end %> 
                </p>
              </ul>
        </div>
      </nav> 
    </div>
  </header>
  <div class="container-fluid"> 
      <div class="row">


          <div class="col-md-2">
            <br>
            <br>
              <p class="img-thumbnail">
              <% if current_user %>
              <%= image_tag current_user.photo.url(:medium), width: '150' %>
              </p>
              <br>
              <br>
              <ins> "<%= current_user.tagline %>"</ins>
              <hr>
              <% end %> 
            <div class="pos_fixed">
              <img src="<%= asset_path('mythai4.svg') %>" alt="myThai">
              <p>" ..do you myThai?"</p>
            </div>
          </div>



          <div class="col-md-10">
            <%= yield %>
          </div>
          
      </div>
    </div>


  </body>
</html>

app/views/thaifoods/_form.html.erb
<div class="container-fluid"> 
  <div class="row">
    <div class="col-md-1"></div>
      <div class="col-md-9">

            <h1 id="loginready"> Add your dish! </h1>

                <%= form_for @thaifood do |f| %>
                  Dish Name: 
                  <%= f.text_field :dish, class: 'form-control' %>
                  Location: 
                  <%= f.text_field :location, class: 'form-control' %>
                  Restaurant: 
                  <%= f.text_field :restaurant, class: 'form-control' %>
                  Unit Price $
                  <%= f.number_field :price_per_dish, :step => 0.01, class: 'form-control' %>
                  <br> 
                  
                  Add your Thai Dish: 
                  <%= f.file_field :photo %><br>

                  <%= f.submit 'Add/Edit Your ThaiDish!', class: 'form-control btn btn-primary' %>
              
          <% end %>

        </div>
    </div>
</div> 

app/views/thaifoods/edit.html.erb
<%= render partial: "form" %>

app/views/thaifoods/index.html.erb
<div class="container-fluid"> 

  <hr>
    <h4><%= link_to 'Add a New Dish!', new_thaifood_path %></h4>

    <table class="table table-hover table-bordered table-condensed">

        <thead>
          <th>Picture</th>
          <th>Name</th>
          <th>Location</th>
          <th>Restaurant</th>
          <th>Price</th>
          <th>Edit & Delete</th>
          <th>Comment</th>
          <th>Timestamps</th>
          <th>RATING!</th>
          <th>#</th>
        </thead>
        
        <% if @thaifoods  %>

        <tbody>
          <% @thaifoods.each do |i| %>
          <tr>
            <td><%= image_tag i.photo.url(:small), alt: "#{i.dish.downcase}image", width: '100' %></td>   
            <td><%= i.dish.downcase %></td>
            <td><%= i.location %> </td>
            <td><%= i.restaurant %></td>
            <td>$<%= i.price_per_dish %></td>
            <td><%= link_to 'Edit', edit_thaifood_path(i), class:'btn btn-default btn-sm right' %><%= button_to 'DELETE', i, method: :delete %> </td>
            <td><%= link_to "Comment this!", i %></td>
            <td><%= "#{i.date_published}" if i.created_at %></td>
              <td> <%= form_for i do |x| %>  
                Your dish rating! <%= x.select :rating, options_for_select([ "1", "2", "3", "4", "5"]) %>
               <%= x.submit 'Your Rating', class: 'form-control btn btn-success'  %> </td>
               <td> <%= i.rating %> </td>
            <% end %>
           </tr>
            <% end %>
            <% end %>
        </tbody>
    </table> 
</div> 

app/views/thaifoods/new.html.erb
<%= render partial: "form" %>

app/views/thaifoods/show.html.erb
<div class="container-fluid">
    <div class="row">
      <div class="col-md-1"></div>
          <div class="col-md-9">
          
            <div class="backright"> 

              <p class="backbutton"> <%= link_to "Back", thaifoods_path, class:'btn btn-default btn-sm left'  %> </p> 

                <p class="comments">C O M M E N T S</p></div>
              <hr>

                <div class="picturetag">
                  <%= image_tag @thaifood.photo.url(:medium), alt: "#{@thaifood.dish.downcase}image", width: '450' %>

                    <div class="comdes"> 
                    <p><mark><%= @thaifood.dish %> @
                    <%= @thaifood.restaurant %></mark></p>
                    <br>
                    <br>
                    <p> 
                    <mark> <%= @thaifood.location %></p><p>
                    <br><br> <ins>- RATING: <%= @thaifood.rating %></mark></ins></p>
                    </div>
                   
              </div> 
              
              <hr> 
            
                 <% @thaifood.comments.each do |comment| %>
                 <%= comment.body %> 

                <p class="timeright">
                  <%=  %><small><%= comment.created_at.localtime.strftime("%A, %B %-d, %Y at %l:%M %p") if comment.created_at %> <%= comment.user.username if comment.user %> </small>
                </p> 
                
                 <% end %>

              <h5>Add a comment:</h5>
              <%= form_for [@thaifood, @new_comment] do |f| %> <p class="textarea2">
                <%= f.text_area :body, class:'form-control wide-comment' %> </p>
                <%= f.submit "Submit", class:'btn btn-sm btn-primary comment' %><small> <%= current_user.username %></small>
                <% end %>
        </div>
       </div>
</div>  

app/views/users/index.html.erb
<div class="container-fluid">
	<br>
		<div class="jumbotron">
			<h1> Helping you find the <span> perfect Thai</span> dish YOU'RE craving!</h1>
			<hr> 
			<p> <img src="<%= asset_path('tomyum1.jpg') %>" alt="myThai" class="img-thumbnail">
			 <img src="<%= asset_path('padthai3.jpg') %>" alt="myThai" class="img-thumbnail"> 
			 <img src="<%= asset_path('papayasalad1.jpg') %>" alt="myThai" class="img-thumbnail">
			</p>
		</div>
		<hr> 
		
		<small>Copyright © 2000–2015 BenSam Inc. MyThai burst and related marks are registered trademarks of BenSam Corporation.<small> 
	
</div>

app/views/users/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-1"></div>
			<div class="col-md-9">
				<h1 id="loginready"> Signup! </h1>

					<%= form_for(@user) do |f|%>
						<p class="headline">
					  		Email: <%= f.text_field :email, class: "form-inline form-control" %>

					  		First Name: <%= f.text_field :firstname, class: "form-label form-control" %> 
				

					  		Last Name: <%= f.text_field :lastname, class: "form-control" %>
		

					  		Username: <%= f.text_field :username, class: "form-control" %>

					  		Password: <%= f.password_field :password, class: "form-control" %>

					  		Confirm password:
					    		<%= f.password_field :password_confirmation, class: "form-control" %> <br>

					  
					  		Upload your profile picture: 
					 		 <%= f.file_field :photo %> <br>
							 <%= f.submit "Signup!", class: 'form-control btn btn-primary ' %> 

					  		<p class="shoutoutright">
					  		Your ThaiFood Shoutout!<%= f.text_area :tagline, class: "form-control comment" %> </p>
					  		</p>

					<% end %>

					<p class="signuppix">
					  	<img src="<%= asset_path('signupdish.jpeg') %>" alt="myThai" class="img-thumbnail">
					</p> 

					<h4> 
						... I want some myThai! </h4> 

			</div>
	</div>
</div> 